### ISSUE TITLE
Why no MoarPeripherals?

### ISSUE THREAD

**Issue by theoriginalbit** [SoniEx2/NBSPlayer#2]
I know that [MoarPeripherals](http://moarperipherals.com) already has an NBS player (and NBS reading API) called [`note`](https://github.com/theoriginalbit/MoarPeripherals/blob/master/src/main/resources/assets/moarperipherals/lua/note.lua), but you could still make your program support the MoarPeripherals [Iron Note Block](http://moarperipherals.com/index.php?title=Iron_Note_Block).

**Comment by SoniEx2** [comment]
> instrument, pitch
> 
> Note that this function will error if asked to play more than five notes (six in versions prior to 1.3) within a tenth of a second. 
> 
> Only 5 instruments

Haha no.

https://github.com/asiekierka/Computronics/issues/109

https://github.com/asiekierka/Computronics/blob/master/src/main/java/pl/asie/computronics/util/NoteUtils.java#L10

(etc. basically Computronics is much more advanced than that POS you just linked.)

(Not counting that my thing will happily take 20 TPS songs - something no other NBS player has done before mine)

Oh and I'm making a modular rewrite to support [NBX](/eNByEx) as well.

**Comment by theoriginalbit** [comment]
Hey I'm fine with you not adding support, MoarPeripherals has a much better program than this anyway, just thought it could be nice for you to add support for other mods that add the same block and potentially gain more users of your program, you don't have to be a dick about it.

You requested volume be added to Computronics, there was no reason you could not do the same for MoarP otherwise the only other difference is these two additional note sounds, definitely not justifiable in calling the one in MoarP a PoS – which btw if you think that about the one in MoarP you should try using the very first Iron Note Block, the one from MiscPeripherals.

**Comment by SoniEx2** [comment]
This was originally made for MiscPeripherals. MiscPeripherals supported 5 notes / twentieth (1/20) of a second (aka 1 tick), not 5 notes / tenth (1/10) of a second (aka 2 ticks), so I could play 20 TPS songs with it.

Also can the MoarP thing play 13.25 TPS songs (at approximately 13.25 TPS)? or only 10 / 5 / 2.5 TPS songs? Does it suffer from dan200/ComputerCraft#10 as well? (this is only supported on branch `ats`, still gotta merge it into master)

NBX will soon add support for panning (left / right / both / off) and coroutines (kinda complicated but **similar** to [this](https://gist.github.com/SoniEx2/c679e771d506210378a5)), so this is gonna end up being MUCH better than ANY existing system.

The modular system I'm developing is gonna make supporting both NBS and NBX very painless, I just have to check for the NBX file signature, if it's not there then I'll fall back to NBS. NBX also makes parsing/loading easier. (even if it's currently just a WIP)

I've been making this since MC 1.5.2(I think?) ([I still have the original world!](http://www.mediafire.com/download/kr12tvhnf4qjr3n/world.zip)), MoarP exists since 1.6.4.

**Comment by theoriginalbit** [comment]
> This was originally made for MiscPeripherals. MiscPeripherals supported 5 notes / twentieth (1/20) of a second (aka 1 tick), not 5 notes / tenth (1/10) of a second (aka 2 ticks), so I could play 20 TPS songs with it.

That seems to be an error on the behalf of the wiki administrator. MoarP sends the notes to clients every game tick. Sending the notes per tick, as opposed to per note, is done to significantly improve reliability in multiplayer without effecting playback.

> Also can the MoarP thing play 13.25 TPS songs (at approximately 13.25 TPS)? or only 10 / 5 / 2.5 TPS songs?

It is not limited to 10 / 5 / 2.5 TPS songs, unless the author of the `note` program has recently changed that – which I will admit there were changes made recently though I can't remember what they were.

**Comment by SoniEx2** [comment]
I would happily support it if it were as good or better than Computronics. Currently this isn't the case. I'll try to push the modular system so you can start writing your own modules.

**Comment by theoriginalbit** [comment]
At the very least what do you feel would need to be added to make it "as good or better than Computronics"? Other than volume – which is really easy enough to add, I just never did.

**Comment by SoniEx2** [comment]
To make it better: Support all instruments that come with vanilla (standard note block instruments + pling + bass), **and add an API to allow registering new instruments**. (ofc, you should accept strings for `instrument`)

**Comment by theoriginalbit** [comment]
> and add an API to allow registering new instruments.

I assume you mean Lua-side? So they'd have a sound file in the computer and then do

``` Lua
noteBlock.registerInstrument("name", "path/on/computer/inst.ogg")
```

**Comment by SoniEx2** [comment]
No, Java side, so mods that add extra instruments can add them to your note blocks.

**Comment by theoriginalbit** [comment]
Right, can do.

**Comment by SoniEx2** [comment]
It'd probably involve a `HashMap<String, String> instrumentToName = new HashMap<String, String>()` and then vanilla notes would be:

```
"minecraft:piano" -> "minecraft:note.harp"
"minecraft:clicks" -> "minecraft:note.hat"
"minecraft:snare" -> "minecraft:note.snare"
"minecraft:bassguitar" -> "minecraft:note.bassattack"
"minecraft:bassdrum" -> "minecraft:note.bd"
"minecraft:guitar" -> "minecraft:note.pling"
"minecraft:bass" -> "minecraft:note.bass"
```

(I'd also register XP orb and anvil falling but that's just me :P)

And mods would register their instruments as "modid:instname" - > "modid:soundname".

**Comment by theoriginalbit** [comment]
I wasn't aware that `pling` and `bass` were vanilla sounds.

**Comment by SoniEx2** [comment]
Are you sure it doesn't work with MP? I mean, have you even tried? (volume probably won't work but other than that it should work)

**Comment by theoriginalbit** [comment]
well the volume argument meant that MoarP would reject the call. also I'm pretty sure that MoarP has a different peripheral name than MiscP, though I could be wrong. finally it's not listed as compatible in your [readme](https://github.com/SoniEx2/NBSPlayer/blob/master/README.md).

**Comment by SoniEx2** [comment]
You're not listed as compatible because I didn't know about you.

Also,

> the volume argument meant that MoarP would reject the call.

You should fix that, because the Lua way is to silently ignore extra arguments.

**Comment by theoriginalbit** [comment]
not with peripherals, peripherals reject calls if there are too many or not enough arguments or if they're the wrong type, even with ComputerCraft peripherals. Also if I were to allow the ignoring of extra arguments it will make the future expansion of theoriginalbit/Peripheral-Framework#3 impossible.

**Comment by SoniEx2** [comment]
The Lua way is to ignore extra arguments. If ComputerCraft doesn't respect the Lua way it's their problem, but I recommend every developer who wants to use Lua to do it.

And what do you mean it'll be impossible? Look at how Lua does it.

http://www.lua.org/manual/5.1/manual.html#pdf-loadstring (you can pass string and chunkname followed by garbage)

http://www.lua.org/manual/5.1/manual.html#pdf-table.insert (passing 3 args makes it assume `(table, pos, value)`, passing more than 3 also makes it assume `(table, pos, value)`)

You get the idea.

**Comment by theoriginalbit** [comment]
I am well aware of how Lua deals with the arguments, I have dealt with Lua extensively. However, how Lua deals with the extra arguments means that it does not support the following:

``` Lua
local function a(b)
end

local function a(b, c)
end
```

instead you must do

``` Lua
local function a(b, c)
  if c == nil then
    -- do something
  else
    -- do something else
  end
end
```

whereas in Java we can do the following

``` Java
public void a(int b) {
  // do something
}

public void a(int b, int c) {
  // do something else
}
```

also since peripherals are written in Java it is best that all Java types are supported (such as `int`) even though Lua doesn't have as large of a selection (for example it only has `double` no `int` or `float` or `short`, etc) as such the [Peripheral-Framework](https://github.com/theoriginalbit/Peripheral-Framework) deals with automatic conversion from the `double` to the `int` or whatever is required of the method to call it. However the further issue comes in where primitives cannot be `null` meaning if we had a method defined like so

``` Java
public void a(int b, int c) {
}
```

it means that if we wanted the `c` parameter to be an optional there is no way to support this because it **needs** to have a value. I could force the methods into using the object form of primitives (like `Integer`) which can be `null`, but then that collides with the first issue of they should be able to use any Java type and it be able to convert from Lua to Java. Therefore the best solution is to allow method overloading as such

``` Java
public void a(int b) {
  a(b, -1); // allow the developer to chose the default or 'null' value
}

public void a(int b, int c) {
}
```

meaning that from the Lua-side they must also be forced into providing the correct number of arguments for this conversion to happen.

**Comment by SoniEx2** [comment]
**Extra** arguments won't cause issues with the conversion, just eat the last argument until it fits a method. Alternatively error if:

``` java
public void a(int b, int c){}
public void a(int b){}
```

Is called from Lua as:

``` lua
a(1, "b", 2)
```

Because, doing it like Lua, it would eat the `2` and try to match against `public void a(int b, int c)`, but in this case `"b"` is a string and cannot be converted to an integer.

This is the Lua way. This is how you do it.

**Comment by theoriginalbit** [comment]
thinking about this now it is possible to do this, however there would only be one way to process this, see the simplified code below

``` Java
public Object[] call(String method, Object... args) {
  List<Object> arguments = new ArrayList<>(args);

  while (!arguments.isEmpty()) {
    for (MethodWrapper m : methodList) {
      if (accepts(m, arguments)) {
        return invoke(m, arguments)
      }
    }
    // consume the last argument
    arguments.remove(arguments.length() - 1);
  }

  throw new Exception("Cannot find method to match arguments");
}

private boolean accepts(MethodWrapper method, List<Object> args) {
  // convert the args based off what the method expects
  return conversionSuccessful;
}

private Object[] invoke(MethodWrapper method, List<Object> args) {
  // convert the args based off what the method expects
  return m.invoke(convertedArgs);
}
```

the above code adds a lot of overhead with the amount of loops required, as well as the constant type conversion... think about an Iron Note block calling this 20 times a second, and it having to do this process _every_ time.

**Comment by SoniEx2** [comment]
Maybe don't arguments.remove(arguments.length() - 1); just calculate with the different length and oh wait this is reflection...

Ugh :/

This is why just passing a bloody array is easier...

**Comment by SoniEx2** [comment]
Wait I know, you can precalculate the min and max number of arguments a certain function can take. If it's < min, error, if it's > max, drop (this is actually fast because they're quite cheap operations) and try calling, or error if it's incompatible.

This is the Lua way and the cheapest way I can think of.

**Comment by theoriginalbit** [comment]
even doing it with an array would still have the same overhead. plus argument consumption is needed after checking _each_ method, otherwise there are circumstances where some methods may always be called, take the following example.

Processing code:

``` Java
public Object[] call(String method, Object... args) {
  for (MethodWrapper m : methodList) {
    Object[] result = tryInvoke(m, args);
    if (result != null) {
      return result;
    }
  }

  throw new Exception("Cannot find method to match arguments");
}

private Object[] tryInvoke(MethodWrapper m, Object[] args) {
  // consume args until length of args is the same as method args
  // concert args to match method args
  return convertSuccess ? m.invoke(convertedArgs) : null;
}
```

Java peripheral code:

``` Java
@Function
public void a(int b) {
}

@Function
public void a(int b, int c) {
}
```

Lua peripheral call

``` Lua
p.a(1, 2);
```

the first method would always be called because the consume would always work.

**Comment by SoniEx2** [comment]
If so, you're doing it wrong. `p.a(1, 2)` is very cheap to see it has 2 arguments, and you know there's a function with 2 arguments (as it's the max number of arguments) so you try to call the functions with 2 arguments, one after the other, and if all of them fail you error.

**Comment by theoriginalbit** [comment]
No I wouldn't be, you said to remove the `arguments.remove(arguments.length() - 1);` which to do that means that each method would have to try to consume arguments to check a match. This means there could be false matches where the arguments do match but there was another method it was actually intended for; like in the above stated case.

**Comment by SoniEx2** [comment]
/me facepalms

The Lua way means:

Has 3 functions

``` java
@Function
public void a(int b) {
}

@Function
public void a(String b, int c) {
}

@Function
public void a(int b, int c) {
}
```

The class would generate bindings, and while generating bindings it would notice:
- a(int) can take 1 argument
- a(int, int) can take 2 arguments
- a(String, int) can take 2 arguments
- min number of arguments: 1, max number of arguments: 2

The call:

``` lua
p.a(1, 2)
```

Would do:
- Number of arguments in call: 2
- Compare to min number of arguments
  - If `nargs < min`, error
  - Else keep going
- Compare to max number of arguments
  - If `nargs > max`, drop until `nargs = max`
  - Else keep going
- Find a match based on `nargs`
  - Possible matches for a, 2 arguments:
    - `a(int, int)`
    - `a(String, int)`
  - Compatible matches for arguments `(1, 2)`:
    - `a(int, int)`
  - If none are found, error
- Call it

This is the cheapest you can get. And trust me it's very cheap. (Much cheaper than the other way)

**Comment by theoriginalbit** [comment]
hmmm possibly. I'll have a play with it when I get some free time in a week or so and see how it goes.

though with the way you stated it only tries the methods with 2 args, it doesn't attempt the one that only has 1 arg, which if we were in Lua it would drop all the extra args to call the one with a single arg.
